### ISSUE TITLE
Trailing white space in IP DB value with MSSQL

### ISSUE THREAD

**Issue by mrfroggg** [Werneror/django-cidrfield#1]
I'm using MSSQL database with Django and found that it fills the char field with spaces (to match the max lenght specified (150).

This causes problem on parsing the IP value.

I'm creating a small PR to fix this potential issue.

Cedric

**Comment by mikeokner** [comment]
I ran into the same issue with Postgres. I was able to work around it by manually changing the column type to varchar after table creation.

```sql
ALTER TABLE app_network ALTER COLUMN cidr TYPE varchar(150);
```
